# Generated by Django 2.2.1 on 2019-06-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190612_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
