# Generated by Django 2.2.1 on 2019-06-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
